security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
#        app_user_provider:
#            entity:
#                class: App\Entity\User
#                property: username

        api_user_provider:
            entity:
                class: App\Entity\User
                property: apiToken

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            logout: ~

            guard:
                provider: api_user_provider
#                entry_point: App\Security\JsonAuthenticator
                authenticators:
                    - App\Security\TokenAuthenticator
#                    - App\Security\JsonAuthenticator

    access_control:
        - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_USER }
