security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        api_user_provider:
            entity:
                class: App\Entity\User
                property: apiToken

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/
            stateless: true
            anonymous: true
            provider: api_user_provider
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
        main:
            pattern: ^/
            anonymous: true
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: /login
            guard:
                authenticators:
                    - App\Security\JsonAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
#                 target: /api

    access_control:
        - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_USER }
